#!/bin/sh
set -x
ssh ubuntu@172.31.13.92<<EOF
    cd ~/node-app
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install v12.0.0
    npm install
    npm install pm2 -g
    pm2 delete all
    pm2 start ecosystem.js
    pm2 save
    pm2 startup
    exit
EOF
